config/routes.rb
# frozen_string_literal: true

# Class comment
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies,  through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
# frozen_string_literal: true

# Class comment
class BookmarksController < ApplicationController
def new
  @bookmark = Bookmark.new()
  @list = List.find(params[:list_id])

end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    
    
    @bookmark.save

    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

# Class comment
class ListsController < ApplicationController
  def index
    @lists = List.all
    
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save

    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for @bookmark do |f| %>
  <%= f.input :movie_id, :collection => @movies %>
  <%= f.input :list_id, as: :hidden, input_html: { :value => @list.id }%>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
<%= f.input :comment %>
<%= f.association :movie %>
<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="form-body">
        <div class="row">
            

<div class=" form-group my-3 mx-auto" style="width: 500px">
<%= simple_form_for(@list) do |f| %>




  <div class=" form-content rounded py-5 mb-4">
    <div class="form-inputs form-control">
    <%= f.input :name, input_html: { class: "" }, 
          label: "Name of the new list", 
          required: true %>
    <%= f.input :photo, as: :file %>
  
  </div>
<div class="d-flex justify-content-center"><div class=" my-3 mx-2 bg-primary btn btn-ghost btn-block">
    <%= f.button :submit %>
  </div></div>
  
<% end %>

  </div>



</div></div></div>

app/views/lists/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "kinokarte.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home",  lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "New list", new_list_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/mazgio", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<%= render "navbar", list: @list %>

<div class="d-flex justify-content-around">
  <div class="align-items-center">
    <% if !@lists.empty? %>
      <% @lists.each do |list| %>
        <% if list.photo.present? && list.photo.key.present? %>
        <%= link_to list_path(list), class: "list-name" do %>
          <div class="my-4 card-category"  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')"> <p><%= list.name %></p></div>
          <% end %>
        <% else %>
          <%# raise %>
         <div class="m-auto"><%= image_tag "default_image.jpg", height: 300, width: 400 %></div> 
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div><%= render "navbar", list: @list%></div>
<!-- app/views/pages/home.html.erb -->
<div class="banner" style="background-image: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), url('<%= asset_path("movie_banner.jpg") %>')">
  <div class="container">
    <h1>Cinema where you can <strong>find your movie</strong></h1>
    <p>Create your favorite list of movies</p>
  </div>
</div>

<%= render "form", list: @list %>

<br>

<div class="d-flex text-align-center">
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<p style="color: green"><%= notice %></p>

  <%# render partial: "movies/movie"%>

<p><strong><%= @list.name %></strong></p>
    

<%#= render "bookmarks/form" %>

<div>
  <% @list.bookmarks.each do |bookmark|%>
  <h2><%=bookmark.movie.title  %></h2>
   <%= image_tag(bookmark.movie.poster_url)   %>

  
  <% end %>



  <%# link_to "Add this movie", edit_movie_path(@movie) %> 
  <%# link_to "Back to movies", movies_path %>

  <%# button_to "Destroy this movie", @movie, method: :delete %>
</div>
      <%= link_to "Delete",
        list_path(@list),
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

<br>
 <%= link_to "add bookmark",    new_list_bookmark_path(@list) %>
<p> <%= link_to "lists", lists_path %></p>  